#!/bin/bash

# Special thx to @ikokostya
PATCH_FILE="pre-commit.patch"

function clean_up {
    if [ -f "$PATCH_FILE" ]; then
        git apply "$PATCH_FILE" 2> /dev/null
        rm "$PATCH_FILE"
    fi
}

trap clean_up EXIT SIGINT SIGHUP

# Cancel any changes to the working tree that are not going to be committed
git diff > "$PATCH_FILE"
git checkout -- .

# Prevent fixme notes
# http://habrahabr.ru/post/143503/#comment_4810335
git diff --cached | grep ^+ | grep -v pre-commit | grep FIXME --color &&
    echo -e "You probably didn't want to commit these lines.\n#   (use \"git commit -n \" to avoid this check)" &&
    exit 1

GIT_CACHED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

# Lint changed js files
make jshint JSHINT_DIRS="$(echo "$GIT_CACHED_FILES" | grep '\.js$' | xargs echo)" || exit 1

# Run tests for changed js files
TEST_BLOCKS=$(echo "$GIT_CACHED_FILES" | awk '{ system("dirname " $1) }' | grep '^blocks-desktop/' | xargs echo)
if [ "$TEST_BLOCKS" ]; then
    make test TEST_BLOCKS="$TEST_BLOCKS" || exit 1
fi

exit
