#!/bin/bash

# Prevent fixme notes
# http://habrahabr.ru/post/143503/#comment_4810335
git diff --cached | grep ^+ | grep -v pre-commit | grep FIXME --color &&
    echo -e "You probably didn't want to commit these lines.\n#   (use \"git commit -n \" to avoid this check)" &&
    exit 1

GIT_CACHED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

# Check changed js files using jslint
TMP_DIR=$(mktemp -d jshint.XXX)
echo "$GIT_CACHED_FILES" | grep -e '\.js$' --color=none | xargs git checkout-index -f --prefix=$TMP_DIR/
if [ -d $DIR ]; then
    make -C ./$(git rev-parse --show-cdup) jshint JSHINT_DIRS=$TMP_DIR > $TMP_DIR/error.log
    if [ $? -ne 0 ]; then
        sed "s/$TMP_DIR\///g;s/\n/\r/g" $TMP_DIR/error.log
        rm -rf $TMP_DIR
        exit 1
    fi
    rm -rf $TMP_DIR
fi

# Run tests for changed js files using phantomjs
TEST_DIRS=$(echo "$GIT_CACHED_FILES" | awk '/.js$/{gsub("/[^/]+.js",""); s=s " " $0} END {print s}')
if [ "$TEST_DIRS" ]; then
    make test TEST_DIRS="$TEST_DIRS" || exit 1
fi

exit
