#!/bin/bash

# Prevent fixme notes
# http://habrahabr.ru/post/143503/#comment_4810335
git diff --cached | grep ^+ | grep -v pre-commit | grep FIXME --color &&
    echo -e "You probably didn't want to commit these lines.\n#   (use \"git commit -n \" to avoid this check)" &&
    exit 1

GIT_CACHED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

# Check changed js files using jslint
DIR=JSLINT_DIR
echo "$GIT_CACHED_FILES" | grep -e '\.js$' --color=none | xargs git checkout-index -f --prefix=$DIR/
if [ -d $DIR ]; then
    make -C ./$(git rev-parse --show-cdup) jshint JSLINT_DIRS=$DIR > $DIR/error.log
    if [ $? -ne 0 ]; then
        sed 's/JSLINT_DIR\///g;s/\n/\r/g' $DIR/error.log
        rm -rf $DIR
        exit 1
    fi
    rm -rf $DIR
fi

exit
